// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plugin_storage.sql

package sqlc

import (
	"context"
)

const deleteAllPluginStorage = `-- name: DeleteAllPluginStorage :exec
DELETE FROM plugin_storage WHERE plugin_entry_path = ?
`

func (q *Queries) DeleteAllPluginStorage(ctx context.Context, pluginEntryPath string) error {
	_, err := q.db.ExecContext(ctx, deleteAllPluginStorage, pluginEntryPath)
	return err
}

const deletePluginStorage = `-- name: DeletePluginStorage :execrows
DELETE FROM plugin_storage WHERE plugin_entry_path = ? AND key = ?
`

type DeletePluginStorageParams struct {
	PluginEntryPath string
	Key             string
}

func (q *Queries) DeletePluginStorage(ctx context.Context, arg DeletePluginStorageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePluginStorage, arg.PluginEntryPath, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPluginStorage = `-- name: GetPluginStorage :one
SELECT value FROM plugin_storage WHERE plugin_entry_path = ? AND key = ?
`

type GetPluginStorageParams struct {
	PluginEntryPath string
	Key             string
}

func (q *Queries) GetPluginStorage(ctx context.Context, arg GetPluginStorageParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getPluginStorage, arg.PluginEntryPath, arg.Key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getPluginStorageTotalSize = `-- name: GetPluginStorageTotalSize :one
SELECT CAST(COALESCE(SUM(LENGTH(value)), 0) AS INTEGER) AS total_size FROM plugin_storage WHERE plugin_entry_path = ?
`

func (q *Queries) GetPluginStorageTotalSize(ctx context.Context, pluginEntryPath string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPluginStorageTotalSize, pluginEntryPath)
	var total_size int64
	err := row.Scan(&total_size)
	return total_size, err
}

const listPluginStorageEntryPaths = `-- name: ListPluginStorageEntryPaths :many
SELECT DISTINCT plugin_entry_path FROM plugin_storage
`

func (q *Queries) ListPluginStorageEntryPaths(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPluginStorageEntryPaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var plugin_entry_path string
		if err := rows.Scan(&plugin_entry_path); err != nil {
			return nil, err
		}
		items = append(items, plugin_entry_path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPluginStorageKeys = `-- name: ListPluginStorageKeys :many
SELECT key FROM plugin_storage WHERE plugin_entry_path = ?
`

func (q *Queries) ListPluginStorageKeys(ctx context.Context, pluginEntryPath string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPluginStorageKeys, pluginEntryPath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPluginStorage = `-- name: SetPluginStorage :exec
INSERT INTO plugin_storage (plugin_entry_path, key, value) VALUES (?, ?, ?)
ON CONFLICT(plugin_entry_path, key) DO UPDATE SET value = excluded.value
`

type SetPluginStorageParams struct {
	PluginEntryPath string
	Key             string
	Value           string
}

func (q *Queries) SetPluginStorage(ctx context.Context, arg SetPluginStorageParams) error {
	_, err := q.db.ExecContext(ctx, setPluginStorage, arg.PluginEntryPath, arg.Key, arg.Value)
	return err
}
